[package]
name = "crypto-msg-parser-ffi"
version = "0.0.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
crypto-msg-parser = "1.3.9"
serde_json = "1"

[dev-dependencies]
float-cmp = "0.8.0"

[build-dependencies]
cbindgen = "0.16.0"

[profile.release]
lto = true
codegen-units = 1
